<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

/**
 * Seeds the four DABOUQ villa projects shown on the Figma homepage Project
 * Showcase carousel. Featured images are placeholders served from
 * /images/projects/dabouq-N.webp until the designer delivers final renders.
 */
class ProjectsSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'slug' => 'dabouq-3',
                'title_en' => 'DABOUQ 3 PROJECT',
                'title_ar' => 'مشروع دابوق 3',
                'category' => Project::CATEGORY_UNDER_DEVELOPMENT,
                'listing_status' => 'for_sale',
                'group' => 'Dabbouq 7',
                'location_en' => 'Jordan - Amman',
                'location_ar' => 'الأردن - عمّان',
                'address_en' => 'Amman - Dabouq',
                'address_ar' => 'عمّان - دابوق',
                'area_sqm' => 2500,
                'floors' => 3,
                'bedrooms' => 5,
                'bathrooms' => 6,
                'completion_year' => 2026,
                'placeholder' => '/images/projects/dabouq-3.webp',
                'sort_order' => 1,
                'is_featured' => true,
            ],
            [
                'slug' => 'dabouq-4',
                'title_en' => 'DABOUQ 4 PROJECT',
                'title_ar' => 'مشروع دابوق 4',
                'category' => Project::CATEGORY_UNDER_DEVELOPMENT,
                'listing_status' => 'for_sale',
                'group' => 'Dabbouq 7',
                'location_en' => 'Jordan - Amman',
                'location_ar' => 'الأردن - عمّان',
                'address_en' => 'Amman - Dabouq',
                'address_ar' => 'عمّان - دابوق',
                'area_sqm' => 1954,
                'floors' => 3,
                'bedrooms' => 4,
                'bathrooms' => 5,
                'completion_year' => 2026,
                'placeholder' => '/images/projects/dabouq-4.webp',
                'sort_order' => 2,
                'is_featured' => true,
            ],
            [
                'slug' => 'dabouq-5',
                'title_en' => 'DABOUQ 5 PROJECT',
                'title_ar' => 'مشروع دابوق 5',
                'category' => Project::CATEGORY_READY,
                // Sold — used to demo the "Available For Sale" dimming.
                'listing_status' => 'sold',
                'group' => 'Dabbouq 7',
                'location_en' => 'Jordan - Amman',
                'location_ar' => 'الأردن - عمّان',
                'address_en' => 'Amman - Dabouq',
                'address_ar' => 'عمّان - دابوق',
                'area_sqm' => 850,
                'floors' => 2,
                'bedrooms' => 3,
                'bathrooms' => 4,
                'completion_year' => 2025,
                'placeholder' => '/images/projects/dabouq-5.webp',
                'sort_order' => 3,
                'is_featured' => true,
            ],
            [
                'slug' => 'dabouq-6',
                'title_en' => 'DABOUQ 6 PROJECT',
                'title_ar' => 'مشروع دابوق 6',
                'category' => Project::CATEGORY_INVESTMENT,
                'listing_status' => 'for_sale',
                'group' => 'Dabbouq 8',
                'location_en' => 'Jordan - Amman',
                'location_ar' => 'الأردن - عمّان',
                'address_en' => 'Amman - Dabouq',
                'address_ar' => 'عمّان - دابوق',
                'area_sqm' => 2900,
                'floors' => null,
                'bedrooms' => null,
                'bathrooms' => null,
                'completion_year' => null,
                'placeholder' => '/images/projects/dabouq-6.webp',
                'sort_order' => 4,
                'is_featured' => true,
            ],
            [
                'slug' => 'dabouq-7',
                'title_en' => 'DABOUQ 7 PROJECT',
                'title_ar' => 'مشروع دابوق 7',
                'category' => Project::CATEGORY_UNDER_DEVELOPMENT,
                'listing_status' => 'for_sale',
                'group' => 'Dabbouq 8',
                'location_en' => 'Jordan - Amman',
                'location_ar' => 'الأردن - عمّان',
                'address_en' => 'Amman - Dabouq',
                'address_ar' => 'عمّان - دابوق',
                'area_sqm' => 1680,
                'floors' => 2,
                'bedrooms' => 4,
                'bathrooms' => 4,
                'completion_year' => 2027,
                'placeholder' => '/images/projects/dabouq-7.webp',
                'sort_order' => 5,
                'is_featured' => true,
            ],
            [
                'slug' => 'dabouq-8',
                'title_en' => 'DABOUQ 8 PROJECT',
                'title_ar' => 'مشروع دابوق 8',
                'category' => Project::CATEGORY_READY,
                // Reserved — used to demo the "Available For Sale" dimming.
                'listing_status' => 'reserved',
                'group' => 'Dabbouq 8',
                'location_en' => 'Jordan - Amman',
                'location_ar' => 'الأردن - عمّان',
                'address_en' => 'Amman - Dabouq',
                'address_ar' => 'عمّان - دابوق',
                'area_sqm' => 3200,
                'floors' => 3,
                'bedrooms' => 6,
                'bathrooms' => 7,
                'completion_year' => 2025,
                'placeholder' => '/images/projects/dabouq-8.webp',
                'sort_order' => 6,
                'is_featured' => true,
            ],

            // ---------------- FOR RENT ----------------
            [
                'slug' => 'abdoun-1',
                'title_en' => 'ABDOUN 1 PROJECT',
                'title_ar' => 'مشروع عبدون 1',
                'category' => Project::CATEGORY_READY,
                'listing_status' => 'for_rent',
                'location_en' => 'Jordan - Amman',
                'location_ar' => 'الأردن - عمّان',
                'address_en' => 'Amman - Abdoun',
                'address_ar' => 'عمّان - عبدون',
                'area_sqm' => 320,
                'floors' => 2,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'completion_year' => 2024,
                'placeholder' => '/images/projects/abdoun-1.webp',
                'sort_order' => 7,
                'is_featured' => true,
            ],
            [
                'slug' => 'abdoun-2',
                'title_en' => 'ABDOUN 2 PROJECT',
                'title_ar' => 'مشروع عبدون 2',
                'category' => Project::CATEGORY_READY,
                'listing_status' => 'for_rent',
                'location_en' => 'Jordan - Amman',
                'location_ar' => 'الأردن - عمّان',
                'address_en' => 'Amman - Abdoun',
                'address_ar' => 'عمّان - عبدون',
                'area_sqm' => 240,
                'floors' => 1,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'completion_year' => 2023,
                'placeholder' => '/images/projects/abdoun-2.webp',
                'sort_order' => 8,
                'is_featured' => true,
            ],
            [
                'slug' => 'abdoun-3',
                'title_en' => 'ABDOUN 3 PROJECT',
                'title_ar' => 'مشروع عبدون 3',
                'category' => Project::CATEGORY_READY,
                'listing_status' => 'for_rent',
                'location_en' => 'Jordan - Amman',
                'location_ar' => 'الأردن - عمّان',
                'address_en' => 'Amman - Abdoun',
                'address_ar' => 'عمّان - عبدون',
                'area_sqm' => 410,
                'floors' => 2,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'completion_year' => 2024,
                'placeholder' => '/images/projects/abdoun-3.webp',
                'sort_order' => 9,
                'is_featured' => true,
            ],
            [
                'slug' => 'abdoun-4',
                'title_en' => 'ABDOUN 4 PROJECT',
                'title_ar' => 'مشروع عبدون 4',
                'category' => Project::CATEGORY_READY,
                'listing_status' => 'for_rent',
                'location_en' => 'Jordan - Amman',
                'location_ar' => 'الأردن - عمّان',
                'address_en' => 'Amman - Abdoun',
                'address_ar' => 'عمّان - عبدون',
                'area_sqm' => 185,
                'floors' => 1,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'completion_year' => 2022,
                'placeholder' => '/images/projects/abdoun-4.webp',
                'sort_order' => 10,
                'is_featured' => true,
            ],
            [
                'slug' => 'abdoun-5',
                'title_en' => 'ABDOUN 5 PROJECT',
                'title_ar' => 'مشروع عبدون 5',
                'category' => Project::CATEGORY_READY,
                'listing_status' => 'for_rent',
                'location_en' => 'Jordan - Amman',
                'location_ar' => 'الأردن - عمّان',
                'address_en' => 'Amman - Abdoun',
                'address_ar' => 'عمّان - عبدون',
                'area_sqm' => 560,
                'floors' => 2,
                'bedrooms' => 6,
                'bathrooms' => 5,
                'completion_year' => 2025,
                'placeholder' => '/images/projects/abdoun-5.webp',
                'sort_order' => 11,
                'is_featured' => true,
            ],
        ];

        foreach ($rows as $row) {
            unset($row['placeholder']);

            Project::updateOrCreate(
                ['slug' => $row['slug']],
                array_merge($row, [
                    'is_active' => true,
                    'short_description_en' => $row['area_sqm'].' M²',
                    'short_description_ar' => $row['area_sqm'].' م²',
                ]),
            );
        }
    }
}
